import { FlatCompat } from '@eslint/eslintrc';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      '.vitest-scratch/**',
      'data/**',
      'playwright-report/**',
      'test-results/**',
      'StrykerOutput/**',
      '.stryker-tmp/**',
      'next-env.d.ts', // auto-generated by Next.js, regenerated on every build
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      // Strict per the project's own standing instruction: catch real bugs,
      // don't allow silent type-escape hatches or dead code to accumulate.
      '@typescript-eslint/no-explicit-any': 'error',
      // ignoreRestSiblings: the destructure-to-omit idiom (`const { x, ...rest }
      // = obj` to build a payload without field `x`) legitimately never
      // references `x` by name — that's the point, not dead code.
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', ignoreRestSiblings: true }],
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      // 'log' allowed: this app's only observability is stdout (no logging
      // framework, local-first single-user tool) — startup/migration/backup
      // status messages in lib/db.ts and lib/backup.ts are the intended use,
      // not debug leftovers.
      'no-console': ['warn', { allow: ['log', 'warn', 'error'] }],
      // 'smart' (not 'always'): permits `== null` / `!= null` as the
      // standard idiom for "null or undefined", used throughout the API
      // routes for optional DB columns — forcing `!== null && !== undefined`
      // everywhere would be strictly worse, not stricter.
      eqeqeq: ['error', 'smart'],
      'no-var': 'error',
      'prefer-const': 'error',
    },
  },
];

export default config;
